"""add role to users

Revision ID: c8d93ab3e553
Revises: 2740d371a1af
Create Date: 2026-05-05 22:27:37.879779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8d93ab3e553'
down_revision: Union[str, Sequence[str], None] = '2740d371a1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    roles_enum = postgresql.ENUM('user', 'admin', name='rolesenum', create_type=False)
    roles_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', roles_enum, server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    roles_enum = postgresql.ENUM('user', 'admin', name='rolesenum', create_type=False)
    roles_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
